[package]
name = "rust-backend"
version = "1.0.13"
edition = "2024"

[dependencies]
bson = { version = "3.0.0", features = ["serde", "serde_with-3", "chrono-0_4"] }
chrono = { version = "0.4.42", features = ["serde"] }
mongodb = { version = "3.3.0", features = ["sync"] }
serde = { version = "1.0.227", features = ["derive"] }
ureq = { version = "3.1.4", features = ["json"] }
thiserror = "2.0.17"
log = "0.4.28"
env_logger = "0.11.8"
signal-hook = "0.3.18"
once_cell = "1.21.3"
serde_with = "3.16.0"
